#!/usr/bin/env bash
# Data-parallel LoRA across the Mini and the MacBook over Thunderbolt (ring backend).
#
# How it splits: --batch-size is GLOBAL and is divided evenly across workers
# (must be divisible by the number of hosts). Each step, every worker runs its
# half of the batch, gradients are averaged, and the step completes when the
# slowest worker finishes, so the Mini sets the pace.
#
# Usage: scripts/cluster/train_distributed.sh [iters]
#   env: HOSTFILE (default scripts/cluster/hosts.json), BATCH (global, default 8),
#        ADAPTER (default adapters/dictation-dist)
#
# Do not edit this file while a run is in progress (bash reads scripts lazily).
set -euo pipefail
cd "$(dirname "$0")/../.."
source .venv/bin/activate
HOSTFILE=${HOSTFILE:-scripts/cluster/hosts.json}
BATCH=${BATCH:-8}
ADAPTER=${ADAPTER:-adapters/dictation-dist}
ROWS=$(wc -l < evals/data/finetune/dictation/train.jsonl)
ITERS=${1:-$(( ROWS / BATCH ))}       # one epoch
echo "hosts: $(python -c "import json;print([h['ssh'] for h in json.load(open('$HOSTFILE'))])")  rows: $ROWS  global batch: $BATCH  iters: $ITERS"

# ssh "127.0.0.1" in the hostfile means "run locally"; --python must be an absolute
# path that exists on every host (hence identical repo paths).
mlx.launch --backend ring --hostfile "$HOSTFILE" --cwd "$PWD" --python "$PWD/.venv/bin/python" -- \
  scripts/cluster/lora_entry.py \
  --model mlx-community/Llama-3.2-3B-Instruct-4bit \
  --train \
  --data evals/data/finetune/dictation \
  --adapter-path "$ADAPTER" \
  --iters "$ITERS" \
  --batch-size "$BATCH" \
  --grad-checkpoint \
  --clear-cache-threshold 2GB \
  --learning-rate 1e-4 \
  --num-layers 16 \
  --mask-prompt \
  --max-seq-length 512 \
  --steps-per-report 20 \
  --steps-per-eval 500 \
  --save-every 200 \
  --seed 20260915
